[versions]
composeNavigation = "1.3.0"
hilt = "2.56.2"
kotlin = "2.1.20"
agp = "8.1.4"
playServicesWearable = "18.2.0"
coreKtx = "1.15.0"
minSdk = "26"
compileSdk = "35"
ksp = "2.1.20-1.0.32"
androidApp = "8.9.1"
arkAbout = "0.2.0"
activityCompose = "1.10.1"
composeDestinationsVersion = "2.1.0"
arrowFxCoroutines = "1.2.1"
arrowCore = "1.2.1"
constraintlayoutCompose = "1.1.1"
converterGson = "2.9.0"
dagger = "2.50"
datastorePreferences = "1.1.4"
espressoCore = "3.6.1"
firebaseBom = "33.12.0"
glanceAppwidget = "1.1.1"
junit = "4.13.2"
junitVersion = "1.2.1"
lifecycleRuntimeKtx = "2.8.7"
loggingInterceptor = "4.12.0"
material3 = "1.3.2"
navigationComposeVersion = "2.8.9"
orbitMVI = "9.0.0"
qrgenerator = "1.0.1"
retrofit = "2.11.0"
roomRuntime = "2.6.1"
tagcloud = "1.1.0"
timber = "5.0.1"
composeUi = "1.7.5"
workRuntimeKtx = "2.8.1"
appcompat = "1.7.0"
material = "1.12.0"
gson = "2.11.0"
reorderable = "2.4.3"
playReview = "2.0.2"
composeBom = "2023.08.00"
composeMaterial = "1.2.1"
composeFoundation = "1.2.1"
coreSplashscreen = "1.0.1"

[libraries]
androidx-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "composeNavigation" }
ark-about = { module = "dev.arkbuilders.components:about", version.ref = "arkAbout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glanceAppwidget" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }

androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeUi" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeUi" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeUi" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "composeUi" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "composeDestinationsVersion" }
compose-destinations-compiler = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "composeDestinationsVersion" }

arrow-fx-coroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrowFxCoroutines" }
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrowCore" }
constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
play-review = { group = "com.google.android.play", name = "review", version.ref = "playReview" }
play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version = "" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx", version = "" }

junit = { module = "junit:junit", version.ref = "junit" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
orbit-compose = { module = "org.orbit-mvi:orbit-compose", version.ref = "orbitMVI" }
orbit-viewmodel = { module = "org.orbit-mvi:orbit-viewmodel", version.ref = "orbitMVI" }
qrgenerator = { module = "com.github.androidmads:QRGenerator", version.ref = "qrgenerator" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
tagcloud = { module = "io.github.oleksandrbalan:tagcloud", version.ref = "tagcloud" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
reorderable = { group = "sh.calvin.reorderable", name = "reorderable", version.ref = "reorderable" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
androidx-compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
android-application = { id = "com.android.application", version.ref = "androidApp"}
